# Generated by Django 2.1 on 2018-11-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nickname',
            field=models.CharField(default='Guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
