# Generated by Django 2.1 on 2018-11-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20181105_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default='Guest', on_delete=django.db.models.deletion.CASCADE, to='forum.Autor'),
        ),
    ]
